export const PlayersDetails = [
  {
    id: 1,
    name: 'Mateusz Andrzejewski',
    position: 'A',
    skillRate: 5,
  },
  {
    id: 2,
    name: 'Łukasz Błaszczuk',
    position: 'G',
    skillRate: 3,
  },
  {
    id: 3,
    name: 'Przemysław Celadyn',
    position: 'A',
    skillRate: 2,
  },
  {
    id: 4,
    name: 'Dawid Czekała',
    position: 'A',
    skillRate: 2,
  },
  {
    id: 5,
    name: 'Dawid Dąbrowski',
    position: 'D',
    skillRate: 4,
  },
  {
    id: 6,
    name: 'Łukasz Dąbrowski',
    position: 'D',
    skillRate: 2,
  },
  {
    id: 7,
    name: 'Carmine de Lucia',
    position: 'D',
    skillRate: 5,
  },
  {
    id: 8,
    name: 'Michał Jabłoński',
    position: 'A',
    skillRate: 3,
  },
  {
    id: 9,
    name: 'Mateusz Jeż',
    position: 'A',
    skillRate: 1,
  },
  {
    id: 10,
    name: 'Grzegorz Jóźwik',
    position: 'A',
    skillRate: 2,
  },
  {
    id: 11,
    name: 'Szymon Kaczyński',
    position: 'A',
    skillRate: 2,
  },
  {
    id: 12,
    name: 'Paweł Karczewski',
    position: 'A',
    skillRate: 2,
  },
  {
    id: 13,
    name: 'Radosław Kosiński',
    position: 'D',
    skillRate: 3,
  },
  {
    id: 14,
    name: 'Adam Kowalski',
    position: 'D',
    skillRate: 3,
  },
  {
    id: 15,
    name: 'Radosław Kowynia',
    position: 'A',
    skillRate: 5,
  },
  {
    id: 16,
    name: 'Arkadiusz Krawczyk',
    position: 'D',
    skillRate: 2,
  },
  {
    id: 17,
    name: 'Karol Krzyżankiewicz',
    position: 'D',
    skillRate: 1,
  },
  {
    id: 18,
    name: 'Piotr Kuźniewicz',
    position: 'A',
    skillRate: 1,
  },
  {
    id: 19,
    name: 'Michał Kuźniewicz',
    position: 'D',
    skillRate: 3,
  },
  {
    id: 20,
    name: 'Kamil Brol Limok',
    position: 'D',
    skillRate: 2,
  },
  {
    id: 21,
    name: 'Mateusz Malik',
    position: 'A',
    skillRate: 5,
  },
  {
    id: 22,
    name: 'Marcin Markowski',
    position: 'D',
    skillRate: 4,
  },
  {
    id: 23,
    name: 'Tomasz Nowok',
    position: 'A',
    skillRate: 2,
  },
  {
    id: 24,
    name: 'Jakub Piechocki',
    position: 'D',
    skillRate: 2,
  },
  {
    id: 25,
    name: 'Dawid Ptak',
    position: 'A',
    skillRate: 5,
  },
  {
    id: 26,
    name: 'Bartek Sadło',
    position: 'A',
    skillRate: 1,
  },
  {
    id: 27,
    name: 'Mateusz Sochacki',
    position: 'G',
    skillRate: 4,
  },
  {
    id: 28,
    name: 'Wojciech Trojanowski',
    position: 'A',
    skillRate: 1,
  },
  {
    id: 29,
    name: 'Jakub Umywalnik',
    position: 'A',
    skillRate: 3,
  },
  {
    id: 30,
    name: 'Kamil Wawoczny',
    position: 'G',
    skillRate: 4,
  },
  {
    id: 31,
    name: 'Artur Zaczkowski',
    position: 'A',
    skillRate: 1,
  },
  {
    id: 32,
    name: 'Łukasz Kamczyk',
    position: 'D',
    skillRate: 1,
  },
  {
    id: 33,
    name: 'Bartek Ogoński',
    position: 'D',
    skillRate: 2,
  },
  {
    id: 34,
    name: 'Jakub Arka',
    position: 'A',
    skillRate: 3,
  },
  {
    id: 35,
    name: 'Szymon Sujewicz',
    position: 'D',
    skillRate: 3,
  },
  {
    id: 36,
    name: 'Denis Krupa',
    position: 'A',
    skillRate: 1,
  },
  {
    id: 37,
    name: 'Aleksander Cupok',
    position: 'D',
    skillRate: 2,
  },
  {
    id: 39,
    name: 'Maciej Jarząbek',
    position: 'A',
    skillRate: 4,
  },
  {
    id: 40,
    name: 'Rafal Kowalski',
    position: 'D',
    skillRate: 4,
  },
  {
    id: 41,
    name: 'Patryk Wojaczek',
    position: 'A',
    skillRate: 4,
  },
  {
    id: 42,
    name: 'Miłosz Bełbot',
    position: 'D',
    skillRate: 1,
  },
  {
    id: 43,
    name: 'Wojciech Ciołczyk',
    position: 'D',
    skillRate: 1,
  },
  {
    id: 44,
    name: 'Bartosz Botor',
    position: 'D',
    skillRate: 2,
  },
  {
    id: 45,
    name: 'Marcel Piotrowski',
    position: 'D',
    skillRate: 1,
  },
  {
    id: 46,
    name: 'Krystian Hytrek',
    position: 'A',
    skillRate: 1,
  },
  {
    id: 47,
    name: 'Aleksander Rohn',
    position: 'D',
    skillRate: 3,
  },
  {
    id: 48,
    name: 'Aleksander Płatek',
    position: 'A',
    skillRate: 2,
  },
  {
    id: 49,
    name: 'Adam Kudzia',
    position: 'A',
    skillRate: 3,
  },
  {
    id: 50,
    name: 'Piotr Gogolok',
    position: 'A',
    skillRate: 5,
  },
  {
    id: 51,
    name: 'Kamil Gnida',
    position: 'G',
    skillRate: 4,
  },
  {
    id: 52,
    name: 'Fabian X',
    position: 'A',
    skillRate: 1,
  },
  {
    id: 53,
    name: 'Damian Czapski',
    position: 'A',
    skillRate: 2,
  },
  {
    id: 54,
    name: 'Kamil Kasiński',
    position: 'A',
    skillRate: 4,
  },
  {
    id: 55,
    name: 'Mateusz Hauptman',
    position: 'D',
    skillRate: 3,
  },
  {
    id: 56,
    name: 'Marcin Psurek',
    position: 'A',
    skillRate: 1,
  },
  {
    id: 57,
    name: 'anton minelo',
    position: 'A',
    skillRate: 5,
  },
  {
    id: 58,
    name: 'Anton Kolesnyk',
    position: 'D',
    skillRate: 3,
  },
];
